
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/supernova?createDatabaseIfNotExist=true
    username: rmv
    password: 12345
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

jwt:
  secret: 791f3deb-d76a-442a-a149-6d1d520e953b
  expiration: 999999